export enum appActionTypes {
  STATE_CHANGE = 'app/STATE_CHANGE',
  STATE_ACTIVE = 'app/STATE_ACTIVE',
  NAVIGATE = 'app/NAVIGATE',
  SHOW_BOTTOM_SHEET = 'app/SHOW_BOTTOM_SHEET',
  SET_BOTTOM_SHEET_COMPONENT = 'app/SET_BOTTOM_SHEET_COMPONENT',
  SHOW_TABS = 'app/SHOW_TABS',
  CLOSE_BOTTOM_SHEET = 'app/CLOSE_BOTTOM_SHEET',
  CLOSE_TABS = 'app/CLOSE_TABS',
  DISMISS_MODALS = 'app/DISMISS_MODALS',
  CLIPBOARD_READ = 'app/CLIPBOARD_READ',
  CLIPBOARD_WRITE = 'app/CLIPBOARD_WRITE',
}
