export enum appActionTypes {
  STATE_CHANGE = 'app/STATE_CHANGE',
  STATE_ACTIVE = 'app/STATE_ACTIVE',
  NAVIGATE = 'app/NAVIGATE',
  DISMISS_MODALS = 'app/DISMISS_MODALS',
  CLIPBOARD_READ = 'app/CLIPBOARD_READ',
  CLIPBOARD_WRITE = 'app/CLIPBOARD_WRITE',
}
