export enum userActionTypes {
  AUTH_CHANGE_IN_PROGRESS = 'user/AUTH_CHANGE_IN_PROGRESS',
  AUTH_CHANGE_SUCCESS = 'user/AUTH_CHANGE_SUCCESS',
  AUTH_CHANGE_ERROR = 'user/AUTH_CHANGE_ERROR',
  FB_SIGNIN = 'user/FB_SIGNIN',
  GGL_SIGNIN = 'user/GGL_SIGNIN',
  SIGNOUT = 'user/SIGNOUT',
}
